#+TITLE: Géométrie Complexe
#+AUTHOR: 
#+DATE:
#+STARTUP: indent
#+CATEGORY: GeoCom
#+FILETAGS: Main

#+LATEX_CLASS: amsdip
#+LATEX_HEADER: \newtheorem{prop}{Proposition}
#+LATEX_HEADER: \newtheorem{cor}{Corollaire}
#+LATEX_HEADER: \newtheorem{thm}{Theoreme}
#+LATEX_HEADER: \newtheorem{defi}{Définition}

* 0
:PROPERTIES:
:ID:       5ea17f44-adfb-4697-b098-c79f9879518d
:END:      
** Géométrie Riemannienne                                           :metric:
*** [#B] Connection de Levi-Civitta
**** Courbure
***** Ricci
***** Gauss
***** Sectionelle
***** Riemann
*** Surfaces
**** Formule de Gauss-Bonnet
*** Volume riemannien
** Géométrie Complexe
*** Géométrie Hermitienne                                          :metric:
**** Forme hermitienne
***** Connection de Chern
****** Courbure
***** Volume hermitien                                     :CoursDeSerge:
****** Inégalité de Wirtinger
Si $\omega$ forme hermitienne sur $X$
alors
pour toute sous-variété réelle de dimension $2k$ $V \subseteq X$, on a
\[
\int_{V} \omega^k \leq  k! Vol(V)
\]
et avec égalité ssi $V$ est une sous-variété complexe.

\cite{Huybrechts}
****** Théorème Bishop                         :Montel:Wirtinger:Bishop:
cf Cours doctoral Serge.
Utilise inégalité de Wirtinger et théorème de Montel.
**** Géométrie Kahlérienne
**** Laplace-Beltrami
***** Théorie de Hodge
*** Fonctions
**** Fonctions holomorphes
***** Definition
***** Formule de Cauchy-Pompeiu
***** Formule de Cauchy en dimension $n$
***** Hartog-Riemann
***** Wierstrass
**** Sousharmoniques
$Sh(U)$

N'est un faisceau que sur une variété riemannienne.
***** Harmoniques
****** Théorème de l'application conforme               :RiemannMapping:

\begin{thm}[Théorème de l'application conforme (Riemann Mapping Thm)]
Tout ouvert de $\C$
\begin{itemize}
\item non vide
\item différent de $\C$
\item simplement connexe
\end{itemize}
 est biholomorphe au disque unité de $\C$.
\end{thm}

******* Théorème d'uniformisation de Riemann
\begin{thm}
Les surfaces de Riemann simplement connexe sont, à biholomorphismes près :
\begin{itemize}
\item $\C$
\item $\D$ la boule unité de $\C$ (ou le demi-plan de Poincaré)
\item $\Pro^1$
\end{itemize}
\end{thm}
***** Plurisousharmoniques
$PSh(U)$
Faisceau sur une variété complexe.

équivalent à 
\begin{equation}
\forall X \in T_\R M, \quad i(\partial\dbarre f)(X,IX) \geq 0
\end{equation}
(on dit que $i\partial\dbarre f$ est une $(1,1)$-forme positive)
(on voit bien que c'est local ! ?)

****** Pluriharmoniques
$f$ et $-f$ sont plurisousharmoniques

Si $H^1(X,\R) = 0$, alors

$f \in Ph(X)$ \ssi $f$ partie réelle d'une fonction holomorphe
****** Exemples
$z\mapsto \log |z|$ est sousharmonique sur $\C$
donc pour toute fonction holomorphe $f$ sur $X$, $\log |f| \in PSh(X)$

Plus généralement soient $f_i \in \Oo(X)$ et $\alpha_i \geq 0$ pour $1 \leq i \leq n$ alors
\[
\log \left(
|f_1|^{\alpha_1} + \cdots + |f_n|^{\alpha_n}
\right) \in Psh(X)
\]

*** Variétés complexes
**** Holomorphiquement convexe
L'enveloppe holomorphe de chaque compacte est compacte

où l'enveloppe holomorphe de $K$ c'est l'ensemble des points $x$ de la variétés qui sont qui pour toute fonction holo $f$ sur $X$, $|f(x)|$ est borné par le sup de $f$ sur $K$.
***** Surfaces de Riemann
****** Théorème de Riemann-Roch
***** [[./stein.org][Stein]]                                                          :ATTACH:
:PROPERTIES:
:Attachments: stein.org
:ID:       51b17ad0-5ef2-4317-aed0-d2e617759ca8
:END:
***** Compactes
Not enough functions to separate points.
****** Moishezon
Enough meromorphic functions :

Le degré de transcendance sur $\C$ du corps des fonctions méromorphes de $X$ est égal à la dimension complexe de $X$.
******* Projectives (algébriques)
Une variété Moishezon $X$ vérifie~:
$X$ algébrique ssi $X$ est Kahler
******** $\Pro^n$
**** Sous-variétés
***** Espace des cycles                                    :CoursDeSerge:
cf Cours de serge
**** Exemples
- [[./Exemples/K3.org][Surfaces K3]]
** [[./Cohomologie/Cohomologie.org][Cohomologie]]                                                       :ATTACH:
:PROPERTIES:
:Attachments: Cohomologie.org
:ID:       307c2487-843c-45b8-9809-f68f3eb71040
:END:
\input{./Cohomologie/Cohomologie}
** Références
*** Demailly
\cite{Demailly}
*** Morrow-Kodaira
*** Griffith - Harris
*** Claire Voisin
*** Huybrechts
\cite{Huybrechts}
** Kahler
*** Compacte
**** Projective
***** Théorème de Chow                                   :Chow:algebraic:
\begin{thm}[Thm de Chow\label{TheoremChow}\index{theoreme de Chow}]
Projective = Algébrique
\end{thm}
**** Hodge
Metric with kahler form integral in $H^{1,1}$
***** Kodaira embedding thm
Hodge = Projective
** [[./Algebrique/algebrique.org][Géométrie alébrique]]                                               :ATTACH:
:PROPERTIES:
:Attachments: algebrique.org
:ID:       f50c7a16-7566-44c7-8bb8-f40f9b7550e9
:END:
\input{./Algebrique/Algebrique}
* COMMENT A ajouter

** TODO Note mathématique [2016-05-20 ven. 09:23]	    :GEOCOM:NoteMath:
  Liens entre
- Groupe de Chow
- Espace des cycles
En relation avec
- Schema de Hilbert
- Espace de Douady

-Structure de groupe sur l'espace des cycles ?

** TODO Cauchy-Grousat					    :NoteMath:GEOCOM:
:PROPERTIES:
:commit_message: Cauchy-Goursat
:END:
Note mathématique du [2016-05-31 mar. 09:00]

*** Ajouter les notes sur Cauchy-Goursat à Geocom
*** Expliquer la formule de Cauchy et ses applications
sous forme de graphe ?


** TODO Note mathématique du [2016-05-26 jeu. 14:12]	    :GEOCOM:NoteMath:
:PROPERTIES:
:commit_message: changements de trivial. O(k)
:END:
Faire une fiche dans GEOCOM sur les changements de trivialisation de O(k)

*** Sur $\Pro^1$
Recouvrement par des ouverts $U_0, U_\infty$ (isomorphes à $\C$) avec $U_{0\infty} \cong \C^*$. On a des coordonnées $\zeta$ et $\tilde{\zeta}$ sur $U_0$ et $U_\infty$.

**** Avec des coordonnées sur les fibres
Les fibres sur $U_0$ ont une coordonnée $\xi$ et sur $U_\infty$ une coordonnée $\tilde{\xi}$.

Sur $U_{0\infty}$ on a la relation entre les coordonnées sur les fibres
\[
\tilde{\xi} = \zeta^{\pm k}\xi
\]

**** Avec des sections locales

** TODO Connexions Hermite-Einstein, correspondance avec les fibrés vectoriels semi-stables :NoteMath:GEOCOM:
:PROPERTIES:
:commit_message: Hermitian and Hermite-Einstein connections
:END:
Note mathématique du [2016-06-14 mar. 11:14]

*** Hermitian connexion
:SOURCE: From Wikipedia, the free encyclopedia
See also: Holomorphic vector bundle § Hermitian metrics on a holomorphic vector bundle 
:END:      

In mathematics, a Hermitian connection ∇ {\displaystyle \nabla } , is a connection on a Hermitian vector bundle over a smooth manifold which is compatible with the Hermitian metric. If the base manifold is a complex manifold, and the Hermitian vector bundle admits a holomorphic structure, then there is a canonical Hermitian connection, which is called the Chern connection which satisfies the following conditions

    Its (0, 1)-part coincides with the Cauchy-Riemann operator associated to the holomorphic structure.
    Its curvature form is a (1, 1)-form.

In particular, if the base manifold is Kähler and the vector bundle is its tangent bundle, then the Chern connection coincides with the Levi-Civita connection of the associated Riemannian metric

*** QUOTE from nLab
The Kobayashi-Hitchin correspondence states that over suitable complex manifolds the moduli space of semi-stable vector bundles and that of Hermite-Einstein connections are essentially the same.

For the special case over Kähler manifolds this is the Donaldson-Uhlenbeck-Yau theorem. For the special case over Riemann surfaces it is the Narasimhan-Seshadri theorem. See also Deligne’s characterization of intermediate Jacobians (in particular there at Examples – Picard variety).

-
- see [[https://ncatlab.org/nlab/show/Kobayashi-Hitchin+correspondence][Kobayashi-Hitchin correspondance]]
- à relier avec l'article de Verbitsky

** TODO Cohomologie de dimension infinie                          :NoteMath:
:PROPERTIES:
:commit_message: Cohomologie de dimension infinie
:END:
Note mathématique du [2016-06-21 mar. 15:36]

Est-ce que $H^1(Z,\Oo_Z)$ peut être de dimension infinie même si $Z$ est compact ?

Sur une variété Kahlérienne, on a la représentation de Hodge des espaces de Coh, et ça doit entraîner la compacité. D'autre part sur une variété Stein, les faisceaux de $\Oo$-modules n'ont pas de coh supérieure...

*** Réponse de Christophe
La théorie de Hodge marche pour n'importe quelle variété complexe compacte. Etant donnée une métrique hermitienne (il y en a plein), on peut construire un laplacien, qui est elliptique, les forme harmoniques sont donc en dimension finie. Cet espace de forme harmoniques représente les $H^p(\Omega^q)$

Ce qui est mieux dans le cas Kahlérien, c'est que le laplacien métrique et le laplacien holomorphes sont liés par un facteur $2$, entre autre les formes harmoniques sont fermées et donc ces espaces de formes sont des sous-espaces de la coh de De Rham.

*** Autre
Serre (/Un théorème de dualité/) donne une référence pour tous les faisceaux cohérents sur une variété complexe compacte :
- *H. Cartan* et *J.-P. Serre*, /Un théorème de finitude concernant les variétés analytiques compactes/. Comptes rendu de l'académie des sciences de Paris 237 (1953) p.128--130

** Factorisation de Stein
$f : X \to Y$ propre, alors il existe $X'$ tel que $f$ se factorise en
$X \to X' \to Y$ avec $f : X' \to Y$ propre à fibres géométriquement connexe ($f_* \Oo_{X'} = \Oo_Y$) et $X \to X'$ revêtement fini.

** Dualité de Serre                                        :GEOCOM:NoteMath:
   :PROPERTIES:
   :commit_message: Dualité de Serre
   :END:
 Note mathématique du [2016-07-12 mar. 09:11]
 
Enoncé sous la forme
*** Enoncé
Soit $X$ variété complexe (paracompacte et \(\sigma\)-compacte) de dimension complexe $n$ et $E$ un fibré vectoriel holomorphe sur $X$, alors
\begin{equation}
H^q(X,\Omega^p(E))^\star \simeq H_c^{n-q}(X,\Omega^{n-p}(E^\star))
\end{equation}
en tant qu'espaces de Fréchet.
*** Référence
:Structure: Article
:Title: Un théorème de dualité.
:Author: Jean-Pierre Serre
:Digitized_pages: 18
:gbv-ppn: GDZPPN002056453
:ADBID: 210864

** TODO Théorème de Leray-Hirsch       :GEOCOM:Kunneth:LerayHirsch:NoteMath:
   :PROPERTIES:
   :commit_message: TODO : Ajouter thm de Leray-Hirsch à GeoCom
   :END:
 Note mathématique du [2016-08-25 jeu. 17:29]

- [ ] Ajouter dans la partie "formule de Kunneth".

*** Références
- https://en.wikipedia.org/wiki/Leray%E2%80%93Hirsch_theorem
- Voisin : lemme 7.32 p.171

** Références
- Barlet : /How to .../

** TODO Ajouter la n-complétude à Stein.org                   :GEOCOM:Stein:
:PROPERTIES:
:ASSIGNED: [2016-08-26 ven. 15:32]
:commit_message: TODO : Ajout n-completeness
:END:
# C-c C-s : pour planifier

** Jet bundles

*** Définition
#+Begin_defi
Soit $\Ff$ un faisceau de \(\Oo\)-modules sur une variété $(M,\Oo)$, alors $J^r(\Ff)$ est le faisceau des \(r\)-jets des sections de $\Ff$...
(( À préciser : Est ce qu'on doit supposer $\Ff$ fibré ? ))
#+End_defi
*** Opérateur différentiel

*** Théorème de Peetre

*** Références
- Demailly
- https://en.wikipedia.org/wiki/Jet_bundle
- https://en.wikipedia.org/wiki/Differential_operator#Coordinate-independent_description
- https://en.wikipedia.org/wiki/Peetre_theorem

** Hyperbolicité, MMP et Abondance
Article de Voisin : https://webusers.imj-prg.fr/~claire.voisin/Articlesweb/harvard.pdf

*** General setting

| name /     | Kodaira   | curvature | canonical | hyperbolicity       |
| example    | dimension | (vague)   | (vague)   | (conjectural)       |
|------------+-----------+-----------+-----------+---------------------|
| Fano       | $-\infty$ | positive  | negative  | [MMP, Abundance] :  |
|            |           |           |           | Covered by          |
|            |           |           |           | rational curves     |
|------------+-----------+-----------+-----------+---------------------|
| K3, HK     | $0$       | flat      | trivial   | [Kobayashi] :       |
| Abelian    |           |           |           | Entire curves       |
| CY         |           |           |           | through any         |
|            |           |           |           | point in any        |
|            |           |           |           | direction           |
|------------+-----------+-----------+-----------+---------------------|
| general    | maximal   | negative  | positive  | [Green-Griffiths] : |
| type       |           |           |           | entire curves       |
|            |           |           |           | constrained to      |
|            |           |           |           | subvarieties        |

*** Other dimensions                                    

Other dimensions conjecturally reduce to the previous cases.

**** Dimension de kodaira et additivité
https://en.wikipedia.org/wiki/Kodaira_dimension

    Let $\pi: V \to W$ be an analytic fiber bundle of compact complex manifolds, meaning that $\pi$ is locally a product (and so all fibers are isomorphic as complex manifolds). Suppose that the fiber $F$ is a Moishezon manifold. Then
    \[
    \kappa (V)=\kappa (F)+\kappa (W).
    \]

**** Itaka fibration
Let $X$ be a variety of nonnegative Kodaira dimension over a field of characteristic zero, and let $B$ be the canonical model of $X$, $B = Proj R(X, K_X)$; the dimension of $B$ is equal to the Kodaira dimension of $X$. There is a natural rational map $X \to B$; any morphism obtained from it by blowing up $X$ and $B$ is called the Iitaka fibration. The minimal model and abundance conjectures would imply that the general fiber of the Iitaka fibration can be arranged to be a Calabi-Yau variety, which in particular has Kodaira dimension zero.

*** Abondance

**** Dimension de Kodaira numérique
\[
\kappa(X) = \limsup_{m>0} \dfrac{\log\left(h^0(X,mK_X)\right)}{\log(m)}
\]
et pour $A$ diviseur ample qcq
\[
\kappa_{\text{num}}(X) = \sup_{k>0}\limsup_{m>0} \dfrac{\log\left(h^0(X,mK_X + kA)\right)}{\log(m)}
\]

**** Conjecture d'abondance
\[
\kappa_{\text{num}} = \kappa
\]

It is obvious that 
\[
\kappa_{\text{num}} \geq \kappa
\]
it is called abundance because there would be abundance of sections of powers of the canonical bundle as soon as it has enough numerical bigness.


**** Théorème de Nakayama
Nakayama proved the abundance conjecture for a non-minimal algebraic
variety whose numerical Kodaira dimension is equal to 0:

Theorem. Let $X$ be a smooth projective variety. Assume that the function
$h^0 (X, mK_X + A)$ is bounded (and non vanishing) when $m \to\infty$ for arbitrarily fixed ample divisor $A$. Then there exists a positive integer $m$ such that $H^0 (X, mK_X ) \neq 0$.





** TODO Semi-continuity
- Siu's theorem\\
  https://en.wikipedia.org/wiki/Siu%27s_semicontinuity_theorem
- Some content about Semi-continuity\\
  https://en.wikipedia.org/wiki/Semi-continuity
- Demailly's generalisation
- Example and application, in particular in Algebraic Geometry, number of intersection and other stuffs which might be seen as Lelong numbers.
- Find a moral for these theorems.
- Find a place where to put them.
