#+TITLE: Géométrie Complexe
#+AUTHOR: 
#+DATE:
#+LATEX_CLASS: amsdip
#+LATEX_HEADER: \newtheorem{prop}{Proposition}
#+LATEX_HEADER: \newtheorem{cor}{Corollaire}
#+LATEX_HEADER: \newtheorem{thm}{Theoreme}
#+LATEX_HEADER: \newtheorem{defi}{Définition}
#+STARTUP: indent

* 0
:PROPERTIES:
:ID:       5ea17f44-adfb-4697-b098-c79f9879518d
:END:      
** Géométrie Riemannienne                                           :metric:
*** Connection de Levi-Civitta
**** Courbure
***** Ricci
***** Gauss
***** Sectionelle
***** Riemann
*** Surfaces
**** Formule de Gauss-Bonnet
*** Volume riemannien
** Géométrie Complexe
*** Géométrie Hermitienne                                          :metric:
**** Forme hermitienne
***** Connection de Chern
****** Courbure
***** Volume hermitien                                     :CoursDeSerge:
****** Inégalité de Wirtinger
Si $\omega$ forme hermitienne sur $X$
alors
pour toute sous-variété réelle de dimension $2k$ $V \subseteq X$, on a
\[
\int_{V} \omega^k \leq  k! Vol(V)
\]
et avec égalité ssi $V$ est une sous-variété complexe.

\cite{Huybrechts}
****** Théorème Bishop                         :Montel:Wirtinger:Bishop:
cf Cours doctoral Serge.
Utilise inégalité de Wirtinger et théorème de Montel.
**** Géométrie Kahlérienne
**** Laplace-Beltrami
***** Théorie de Hodge
*** Fonctions
**** Fonctions holomorphes
***** Definition
***** Formule de Cauchy-Pompeiu
***** Formule de Cauchy en dimension $n$
***** Hartog-Riemann
***** Wierstrass
**** Sousharmoniques
$Sh(U)$

N'est un faisceau que sur une variété riemannienne.
***** Harmoniques
****** Théorème de l'application conforme               :RiemannMapping:

\begin{thm}[Théorème de l'application conforme (Riemann Mapping Thm)]
Tout ouvert de $\C$
\begin{itemize}
\item non vide
\item différent de $\C$
\item simplement connexe
\end{itemize}
 est biholomorphe au disque unité de $\C$.
\end{thm}

******* Théorème d'uniformisation de Riemann
\begin{thm}
Les surfaces de Riemann simplement connexe sont, à biholomorphismes près :
\begin{itemize}
\item $\C$
\item $\D$ la boule unité de $\C$ (ou le demi-plan de Poincaré)
\item $\Pro^1$
\end{itemize}
\end{thm}
***** Plurisousharmoniques
$PSh(U)$
Faisceau sur une variété complexe.

équivalent à 
\begin{equation}
\forall X \in T_\R M, \quad i(\partial\dbarre f)(X,IX) \geq 0
\end{equation}
(on dit que $i\partial\dbarre f$ est une $(1,1)$-forme positive)
(on voit bien que c'est local ! ?)

****** Pluriharmoniques
$f$ et $-f$ sont plurisousharmoniques

Si $H^1(X,\R) = 0$, alors

$f \in Ph(X)$ \ssi $f$ partie réelle d'une fonction holomorphe
****** Exemples
$z\mapsto \log |z|$ est sousharmonique sur $\C$
donc pour toute fonction holomorphe $f$ sur $X$, $\log |f| \in PSh(X)$

Plus généralement soient $f_i \in \Oo(X)$ et $\alpha_i \geq 0$ pour $1 \leq i \leq n$ alors
\[
\log \left(
|f_1|^{\alpha_1} + \cdots + |f_n|^{\alpha_n}
\right) \in Psh(X)
\]

*** Variétés complexes
**** Holomorphiquement convexe
L'enveloppe holomorphe de chaque compacte est compacte

où l'enveloppe holomorphe de $K$ c'est l'ensemble des points $x$ de la variétés qui sont qui pour toute fonction holo $f$ sur $X$, $|f(x)|$ est borné par le sup de $f$ sur $K$.
***** Surfaces de Riemann
****** Théorème de Riemann-Roch
***** [[./stein.org][Stein]]                                                          :ATTACH:
:PROPERTIES:
:Attachments: stein.org
:ID:       51b17ad0-5ef2-4317-aed0-d2e617759ca8
:END:
***** Compactes
Not enough functions to separate points.
****** Moishezon
Enough meromorphic functions :

Le degré de transcendance sur $\C$ du corps des fonctions méromorphes de $X$ est égal à la dimension complexe de $X$.
******* Projectives (algébriques)
Une variété Moishezon $X$ vérifie~:
$X$ algébrique ssi $X$ est Kahler
******** $\Pro^n$
**** Sous-variétés
***** Espace des cycles                                    :CoursDeSerge:
cf Cours de serge
**** Exemples
- [[./Exemples/K3.org][Surfaces K3]]
** [[./Cohomologie/Cohomologie.org][Cohomologie]]                                                       :ATTACH:
:PROPERTIES:
:Attachments: Cohomologie.org
:ID:       307c2487-843c-45b8-9809-f68f3eb71040
:END:
\input{./Cohomologie/Cohomologie}
** Références
*** Demailly
\cite{Demailly}
*** Morrow-Kodaira
*** Griffith - Harris
*** Claire Voisin
*** Huybrechts
\cite{Huybrechts}
** Kahler
*** Compacte
**** Projective
***** Théorème de Chow                                   :Chow:algebraic:
\begin{thm}[Thm de Chow\label{TheoremChow}\index{theoreme de Chow}]
Projective = Algébrique
\end{thm}
**** Hodge
Metric with kahler form integral in $H^{1,1}$
***** Kodaira embedding thm
Hodge = Projective
** [[./Algebrique/algebrique.org][Géométrie alébrique]]                                               :ATTACH:
:PROPERTIES:
:Attachments: algebrique.org
:ID:       f50c7a16-7566-44c7-8bb8-f40f9b7550e9
:END:
\input{./Algebrique/Algebrique}
* COMMENT A ajouter

** TODO Note mathématique [2016-05-20 ven. 09:23]	    :GEOCOM:NoteMath:
  Liens entre
- Groupe de Chow
- Espace des cycles
En relation avec
- Schema de Hilbert
- Espace de Douady

-Structure de groupe sur l'espace des cycles ?

** TODO Cauchy-Grousat					    :NoteMath:GEOCOM:
:PROPERTIES:
:commit_message: Cauchy-Goursat
:END:
Note mathématique du [2016-05-31 mar. 09:00]

*** Ajouter les notes sur Cauchy-Goursat à Geocom
*** Expliquer la formule de Cauchy et ses applications
sous forme de graphe ?


** TODO Note mathématique du [2016-05-26 jeu. 14:12]	    :GEOCOM:NoteMath:
:PROPERTIES:
:commit_message: changements de trivial. O(k)
:END:
Faire une fiche dans GEOCOM sur les changements de trivialisation de O(k)

*** Sur $\Pro^1$
Recouvrement par des ouverts $U_0, U_\infty$ (isomorphes à $\C$) avec $U_{0\infty} \cong \C^*$. On a des coordonnées $\zeta$ et $\tilde{\zeta}$ sur $U_0$ et $U_\infty$.

**** Avec des coordonnées sur les fibres
Les fibres sur $U_0$ ont une coordonnée $\xi$ et sur $U_\infty$ une coordonnée $\tilde{\xi}$.

Sur $U_{0\infty}$ on a la relation entre les coordonnées sur les fibres
\[
\tilde{\xi} = \zeta^{\pm k}\xi
\]

**** Avec des sections locales

** TODO Connexions Hermite-Einstein, correspondance avec les fibrés vectoriels semi-stables :NoteMath:GEOCOM:
:PROPERTIES:
:commit_message: Hermitian and Hermite-Einstein connections
:END:
Note mathématique du [2016-06-14 mar. 11:14]

*** Hermitian connexion
:SOURCE: From Wikipedia, the free encyclopedia
See also: Holomorphic vector bundle § Hermitian metrics on a holomorphic vector bundle 
:END:      

In mathematics, a Hermitian connection ∇ {\displaystyle \nabla } , is a connection on a Hermitian vector bundle over a smooth manifold which is compatible with the Hermitian metric. If the base manifold is a complex manifold, and the Hermitian vector bundle admits a holomorphic structure, then there is a canonical Hermitian connection, which is called the Chern connection which satisfies the following conditions

    Its (0, 1)-part coincides with the Cauchy-Riemann operator associated to the holomorphic structure.
    Its curvature form is a (1, 1)-form.

In particular, if the base manifold is Kähler and the vector bundle is its tangent bundle, then the Chern connection coincides with the Levi-Civita connection of the associated Riemannian metric

*** QUOTE from nLab
The Kobayashi-Hitchin correspondence states that over suitable complex manifolds the moduli space of semi-stable vector bundles and that of Hermite-Einstein connections are essentially the same.

For the special case over Kähler manifolds this is the Donaldson-Uhlenbeck-Yau theorem. For the special case over Riemann surfaces it is the Narasimhan-Seshadri theorem. See also Deligne’s characterization of intermediate Jacobians (in particular there at Examples – Picard variety).

-
- see [[https://ncatlab.org/nlab/show/Kobayashi-Hitchin+correspondence][Kobayashi-Hitchin correspondance]]
- à relier avec l'article de Verbitsky

** TODO Cohomologie de dimension infinie                          :NoteMath:
:PROPERTIES:
:commit_message: Cohomologie de dimension infinie
:END:
Note mathématique du [2016-06-21 mar. 15:36]

Est-ce que $H^1(Z,\Oo_Z)$ peut être de dimension infinie même si $Z$ est compact ?

Sur une variété Kahlérienne, on a la représentation de Hodge des espaces de Coh, et ça doit entraîner la compacité. D'autre part sur une variété Stein, les faisceaux de $\Oo$-modules n'ont pas de coh supérieure...

*** Réponse de Christophe
La théorie de Hodge marche pour n'importe quelle variété complexe compacte. Etant donnée une métrique hermitienne (il y en a plein), on peut construire un laplacien, qui est elliptique, les forme harmoniques sont donc en dimension finie. Cet espace de forme harmoniques représente les $H^p(\Omega^q)$

Ce qui est mieux dans le cas Kahlérien, c'est que le laplacien métrique et le laplacien holomorphes sont liés par un facteur $2$, entre autre les formes harmoniques sont fermées et donc ces espaces de formes sont des sous-espaces de la coh de De Rham.
